services:
  web:
    build:
      context: .
      dockerfile: dockerfile
      args:
        arg_pm2_pk: ${PM2_PUBLIC_KEY}
        arg_pm2_sk: ${PM2_SECRET_KEY}
    volumes:
      - "../env:/home/env"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: "1G"
    network_mode: bridge
    ports:
      - "3000:3000"
      - "3080:3080"
      - "3443:3443"
    stdin_open: true
    tty: true
    restart: always
    image: frontend_image
    container_name: frontend_container
